CREATE TABLE `branch_master` (
  `id` varchar(255) NOT NULL,
  `name` varchar(255) DEFAULT NULL,
  `address` varchar(255) DEFAULT NULL,
  `contact_person` varchar(255) DEFAULT NULL,
  `opening_date` varchar(255) DEFAULT NULL,
  `pin` varchar(255) DEFAULT NULL,
  `state` varchar(255) DEFAULT NULL,
  `amount` varchar(255) DEFAULT NULL,
  `from_branch` varchar(255) DEFAULT NULL,
  `to_branch` varchar(255) DEFAULT NULL,
  `transfer_date` varchar(255) DEFAULT NULL,
  `branch_code` varchar(255) DEFAULT NULL,
  `contact_no` varchar(255) DEFAULT NULL,
  `code` varchar(255) DEFAULT NULL,
  `contect_no` varchar(255) DEFAULT NULL,
  `fdate` varchar(255) DEFAULT NULL,
  `tdate` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
);